# Generated by Django 4.2.2 on 2023-06-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('cite', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=50)),
                ('page', models.IntegerField(default=1)),
                ('dateSave', models.DateField(auto_now=True)),
            ],
        ),
    ]
